# Generated by Django 4.1.4 on 2022-12-25 08:58

import api.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(upload_to=api.core.models.product_image_file_path),
        ),
    ]
